rov_passthrough_control_node:
  ros__parameters:
    controller: "joy"

    wrench_topic_name: "joy_wrench"
    wrench_stamped_topic_name: "joy_wrench_stmp"

    send_stamped: True
    frame_id: base_link

    max_norm: 100.0
    max_force: 100.0
    max_torque: 10.0

    equalization_type: "inv_cube"

    joy_topic_name: "joy"

    joy_axis_force_x: 1
    joy_axis_force_y: 0
    joy_axis_force_z: 4

    joy_axis_torque_x: 3
    joy_axis_torque_y: -1
    joy_axis_torque_z: -1

    joy_button_torque_y_pos: -1
    joy_button_torque_y_neg: -1
    joy_button_torque_z_pos: 5
    joy_button_torque_z_neg: 4

    inv_force_x: False
    inv_force_y: False
    inv_force_z: False

    inv_torque_x: False
    inv_torque_y: False
    inv_torque_z: False
