name: Daily Docker Build

on:
  schedule:
    - cron: '30 6 * * *'

jobs:
  build:
    name: Build Docker Container Daily
    runs-on: agh-marines-server
    container: docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout submodules
        run: |
          git config --global --add safe.directory /__w/ROV-ROS2/ROV-ROS2
          git submodule update --init --recursive

      - name: Check
        run: |
          git branch
          ls -l

      - name: Build devcontainer image
        run: |
          docker build -f ./docker/Dockerfile -t ros2-daily-build .

      - name: Cleanup built image
        if: always()
        run: |
          docker rmi ros2-daily-build || true
          docker image prune -f